import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./styles/index.css";
import App from "./App";

// ============================================================
// APP ENTRY POINT
// ============================================================
// This file mounts the React app into <div id="root"> in index.html.
// Do not edit this file unless you need to change the root element.
// ============================================================

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
